version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: /bin/sh
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - .:/tweeter
    ports:
      - "3000:3000"